export const contactPageContent = {
  fr: {
    hero: {
      eyebrow: "Contact",
      title: "Parlons de votre pratique.",
      subtitle:
        "Que vous souhaitiez découvrir une technologie, planifier une démonstration ou rejoindre une masterclass, notre équipe vous répond sous 24 à 48h ouvrées.",
    },
    form: {
      title: "Envoyez-nous un message",
      name: "Nom complet",
      namePlaceholder: "Dr. Jean Dupont",
      email: "Email professionnel",
      emailPlaceholder: "vous@clinique.com",
      phone: "Téléphone",
      phonePlaceholder: "+212 6 00 00 00 00",
      specialty: "Activité",
      specialtyPlaceholder: "Choisissez votre activité",
      specialtyOptions: [
        "Médecin esthétique",
        "Dermatologue",
        "Gynécologue",
        "Chirurgien plasticien",
        "Chirurgien (autre spécialité)",
        "Médecin généraliste",
        "Kinésithérapeute / physiothérapeute",
        "Nutritionniste / diététicien",
        "Centre / institut de beauté",
        "Clinique",
        "Autre",
      ],
      subject: "Objet de la demande",
      subjectOptions: [
        { key: "demo", label: "Demander une démo" },
        { key: "expert", label: "Parler à un expert" },
        { key: "masterclass", label: "Rejoindre une masterclass" },
        { key: "support", label: "Support technique" },
        { key: "devis", label: "Obtenir un devis" },
        { key: "partenariat", label: "Partenariat" },
        { key: "autre", label: "Autre demande" },
      ],
      machine: "Technologie concernée",
      // Message prérempli quand le visiteur arrive depuis une fiche machine ({machine} = nom de la machine)
      machineMessageDemo: "Bonjour, je souhaite organiser une démonstration de {machine}.",
      machineMessage: "Bonjour, je souhaite des informations sur {machine}.",
      message: "Message",
      messagePlaceholder: "Décrivez votre besoin ou votre question…",
      submit: "Recevoir une réponse d'un expert",
      submitting: "Envoi en cours…",
      success: "Merci. Votre message a bien été envoyé — un membre de notre équipe vous recontactera sous peu.",
      error: "Une erreur est survenue. Merci de réessayer ou de nous contacter directement par email.",
      requiredError: "Merci de renseigner ce champ.",
      emailError: "Merci de renseigner une adresse email valide.",
    },
    directContact: {
      title: "Nous contacter directement",
      whatsapp: "WhatsApp",
      call: "Appeler",
      email: "Écrire",
      address: "Adresse",
    },
  },
  en: {
    hero: {
      eyebrow: "Contact",
      title: "Let's talk about your practice.",
      subtitle:
        "Whether you'd like to discover a technology, schedule a demonstration or join a masterclass, our team replies within 24 to 48 business hours.",
    },
    form: {
      title: "Send us a message",
      name: "Full name",
      namePlaceholder: "Dr. Jane Doe",
      email: "Professional email",
      emailPlaceholder: "you@clinic.com",
      phone: "Phone",
      phonePlaceholder: "+212 6 00 00 00 00",
      specialty: "Activity",
      specialtyPlaceholder: "Choose your activity",
      specialtyOptions: [
        "Aesthetic physician",
        "Dermatologist",
        "Gynecologist",
        "Plastic surgeon",
        "Surgeon (other specialty)",
        "General practitioner",
        "Physiotherapist",
        "Nutritionist / dietitian",
        "Beauty center / institute",
        "Clinic",
        "Other",
      ],
      subject: "Subject",
      subjectOptions: [
        { key: "demo", label: "Request a demo" },
        { key: "expert", label: "Speak to an expert" },
        { key: "masterclass", label: "Join a masterclass" },
        { key: "support", label: "Technical support" },
        { key: "devis", label: "Get a quote" },
        { key: "partenariat", label: "Partnership" },
        { key: "autre", label: "Other request" },
      ],
      machine: "Technology of interest",
      machineMessageDemo: "Hello, I would like to arrange a demonstration of {machine}.",
      machineMessage: "Hello, I would like information about {machine}.",
      message: "Message",
      messagePlaceholder: "Describe your need or question…",
      submit: "Get an expert's reply",
      submitting: "Sending…",
      success: "Thank you. Your message has been sent — a member of our team will get back to you shortly.",
      error: "Something went wrong. Please try again or reach us directly by email.",
      requiredError: "Please fill in this field.",
      emailError: "Please enter a valid email address.",
    },
    directContact: {
      title: "Contact us directly",
      whatsapp: "WhatsApp",
      call: "Call",
      email: "Email",
      address: "Address",
    },
  },
} as const;
