export const contactPageContent = {
  fr: {
    hero: {
      eyebrow: "Contact",
      title: "Parlons de votre pratique.",
      subtitle:
        "Que vous souhaitiez découvrir une technologie, planifier une démonstration ou rejoindre une masterclass, notre équipe vous répond sous 24 à 48h ouvrées.",
    },
    form: {
      title: "Envoyez-nous un message",
      name: "Nom complet",
      namePlaceholder: "Dr. Jean Dupont",
      email: "Email professionnel",
      emailPlaceholder: "vous@clinique.com",
      phone: "Téléphone",
      phonePlaceholder: "+225 00 00 00 00 00",
      organization: "Clinique / Cabinet",
      organizationPlaceholder: "Nom de votre structure",
      subject: "Objet de la demande",
      subjectOptions: [
        "Demander une démo",
        "Parler à un expert",
        "Rejoindre une masterclass",
        "Support technique",
        "Autre demande",
      ],
      message: "Message",
      messagePlaceholder: "Décrivez votre besoin ou votre question…",
      submit: "Envoyer le message",
      submitting: "Envoi en cours…",
      success: "Merci. Votre message a bien été envoyé — un membre de notre équipe vous recontactera sous peu.",
      error: "Une erreur est survenue. Merci de réessayer ou de nous contacter directement par email.",
      requiredError: "Merci de renseigner ce champ.",
      emailError: "Merci de renseigner une adresse email valide.",
    },
    directContact: {
      title: "Nous contacter directement",
      whatsapp: "WhatsApp",
      call: "Appeler",
      email: "Écrire",
      address: "Adresse",
    },
  },
  en: {
    hero: {
      eyebrow: "Contact",
      title: "Let's talk about your practice.",
      subtitle:
        "Whether you'd like to discover a technology, schedule a demonstration or join a masterclass, our team replies within 24 to 48 business hours.",
    },
    form: {
      title: "Send us a message",
      name: "Full name",
      namePlaceholder: "Dr. Jane Doe",
      email: "Professional email",
      emailPlaceholder: "you@clinic.com",
      phone: "Phone",
      phonePlaceholder: "+225 00 00 00 00 00",
      organization: "Clinic / Practice",
      organizationPlaceholder: "Your organization's name",
      subject: "Subject",
      subjectOptions: [
        "Request a demo",
        "Speak to an expert",
        "Join a masterclass",
        "Technical support",
        "Other request",
      ],
      message: "Message",
      messagePlaceholder: "Describe your need or question…",
      submit: "Send message",
      submitting: "Sending…",
      success: "Thank you. Your message has been sent — a member of our team will get back to you shortly.",
      error: "Something went wrong. Please try again or reach us directly by email.",
      requiredError: "Please fill in this field.",
      emailError: "Please enter a valid email address.",
    },
    directContact: {
      title: "Contact us directly",
      whatsapp: "WhatsApp",
      call: "Call",
      email: "Email",
      address: "Address",
    },
  },
} as const;
