// Accueil Cellulift — textes repris de cellulift.ma (légèrement resserrés pour les cartes).
// Textes de l'accueil.

export const homeSystem = {
  fr: {
    hero: {
      eyebrow: "Cellulift · Depuis 2002 · Casablanca · Marrakech · Tanger",
      title: ["Complice", "de votre succès."],
      stagger: ["Complice", "de votre", "succès."],
      titleAccent: "Cellulift propose des solutions haut de gamme pour percer dans votre activité.",
      subtitle: "Leader sur le marché des équipements médicaux et spécialisé dans les dispositifs médico-esthétiques.",
      backdrop: ["Medical", "Aesthetic"],
      corner: "Toutes nos machines sont certifiées CE et FDA, avec une garantie de 24 mois pièces et main-d'œuvre.",
      cornerStrong: "Distributeur officiel LGL Expert en Afrique.",
      ctaPrimary: "Obtenez un devis gratuit",
      ctaSecondary: "Nos technologies",
      readout: { label: "Cellulift", status: "", output: "" },
    },
    // Chiffres clés (très grand, sans paragraphe). « {s} » = nombre de showrooms. Ne jamais afficher le nombre de technologies.
    stats: [
      { value: "20+", label: "Ans d'expertise" },
      { value: "1000+", label: "Médecins équipés" },
      { value: "24", unit: "mois", label: "De garantie" },
      { value: "{s}", label: "Showrooms" },
    ],
    // Bandeau défilant sous le hero.
    ticker: [
      "Toutes nos machines sont certifiées CE et FDA",
      "Depuis 2002",
      "Technologies • Installation • Formation • Accompagnement • Service après-vente",
      "5 villes",
      "5 pays",
      "+1000 médecins équipés",
    ],
    system: {
      eyebrow: "01 — Nos fonctionnalités uniques",
      title: "Nos fonctionnalités uniques.",
      intro:
        "Chez Cellulift, nous cultivons notre force dans la créativité et le conseil. Nous mettons en place les mécanismes les plus adaptés à votre fonctionnement pour vous accompagner à réaliser au mieux votre projet.",
      pillars: [
        {
          code: "01",
          name: "Accompagnement",
          title: "Réactivité, écoute et conseil",
          text: "L'équipe Cellulift accompagne ses clients tout le long de leur trajet professionnel, du début jusqu'à l'inauguration de votre projet.",
        },
        {
          code: "02",
          name: "Installation",
          title: "Partout au Maroc",
          text: "Transport adapté, montage et installation de vos machines par nos experts : nous assurons la sécurité de votre matériel et vous épargnons toute la partie technique.",
        },
        {
          code: "03",
          name: "Formation",
          title: "Cellulift Academy",
          text: "Des médecins et spécialistes de renommée nationale et internationale pour faire de vous un expert en médecine esthétique.",
        },
        {
          code: "04",
          name: "Service après-vente",
          title: "Notre atelier",
          text: "En cas de panne, de problème technique ou simplement d'un besoin de conseil, notre atelier accueille vos machines dans les meilleures conditions.",
        },
      ],
    },
    why: {
      eyebrow: "03 — Pourquoi Cellulift ?",
      title: "Pourquoi Cellulift ?",
      intro: "Vous disposerez d'un service unique avec notre équipe d'experts. Accompagnement, conseils et solutions sont nos maîtres mots.",
      items: [
        { title: "Distributeur officiel LGL Expert", text: "Cellulift est le distributeur officiel de la marque LGL Expert en Afrique." },
        { title: "Certifiées CE et FDA", text: "Toutes nos machines sont certifiées CE et FDA." },
        { title: "Garantie 24 mois", text: "Pièces et main-d'œuvre, avec possibilité de déplacement du staff technique." },
        { title: "Les meilleurs formateurs", text: "Nationaux et internationaux, professeurs universitaires et experts du corps et de son bien-être." },
        { title: "Depuis 2002", text: "Plus de 20 ans d'expertise dans les dispositifs médico-esthétiques." },
      ],
    },
    technologies: {
      eyebrow: "02 — Technologies",
      title: "Nos technologies,",
      titleAccent: "par type de soin.",
      intro: "Les dispositifs de dernière génération LGL Expert, dont Cellulift est le distributeur officiel en Afrique, tous certifiés CE Médical et FDA.",
      columns: { ref: "", name: "", category: "", indications: "" },
      viewAll: "Explorer les technologies",
    },
    academy: {
      eyebrow: "04 — Cellulift Academy",
      title: "Devenez expert en médecine esthétique.",
      text: "Formations, workshops et rencontres autour du corps et de sa pleine forme. Rajeunissement, amincissement, physiothérapie et soins du visage ou du corps n'auront plus aucun secret pour vous. Un certificat valide les compétences acquises.",
      facultyLabel: "Formateur",
      cta: "Voir les prochaines formations",
    },
    support: {
      eyebrow: "05 — Service après-vente",
      title: "Nos ingénieurs et techniciens sont à votre écoute, partout.",
      text: "Parce que le bien-être de nos partenaires est primordial, nous avons choisi les meilleurs de la profession pour vous accompagner en cas de besoin.",
      items: [
        { code: "01", title: "Garantie 24 mois", text: "Pièces et main-d'œuvre." },
        { code: "02", title: "Déplacement", text: "Notre staff technique peut se déplacer chez vous." },
        { code: "03", title: "Notre atelier", text: "Vos machines accueillies dans les meilleures conditions." },
        { code: "04", title: "Conseil", text: "Une question technique ? Notre équipe vous répond." },
      ],
      cta: "Réserver maintenant",
    },
    showrooms: {
      eyebrow: "06 — Implantations",
      title: ["One partner.", "Four markets."],
      markets: ["Maroc", "France", "Sénégal", "Arabie saoudite"],
      hq: "Siège",
      onRequest: "Adresse communiquée sur rendez-vous.",
      cta: "Prendre rendez-vous au showroom",
      list: "Showrooms",
    },
    cta: {
      eyebrow: "07 — Notre belle promesse",
      title: "Obtenez un devis gratuit.",
      text: "Nous nous engageons à vous accueillir amicalement et professionnellement, dans un cadre convivial et chaleureux, à respecter vos demandes et à être à l'écoute de vos attentes.",
      ctaPrimary: "Demander un devis",
      ctaSecondary: "Nous appeler",
    },
  },
  en: {
    hero: {
      eyebrow: "Cellulift · Since 2002 · Casablanca · Marrakech · Tangier",
      title: ["Partner", "in your success."],
      stagger: ["Partner", "in your", "success."],
      titleAccent: "Cellulift offers high-end solutions to help your practice break through.",
      subtitle: "A leader in the medical equipment market, specialized in medical aesthetic devices.",
      backdrop: ["Medical", "Aesthetic"],
      corner: "All our devices are CE and FDA certified, with a 24-month parts and labour warranty.",
      cornerStrong: "Official LGL Expert distributor in Africa.",
      ctaPrimary: "Get a free quote",
      ctaSecondary: "Our technologies",
      readout: { label: "Cellulift", status: "", output: "" },
    },
    stats: [
      { value: "20+", label: "Years of expertise" },
      { value: "1000+", label: "Physicians equipped" },
      { value: "24", unit: "months", label: "Warranty" },
      { value: "{s}", label: "Showrooms" },
    ],
    ticker: [
      "All our devices are CE and FDA certified",
      "Since 2002",
      "Technology • Installation • Training • Support • After-sales service",
      "5 cities",
      "5 countries",
      "1,000+ physicians equipped",
    ],
    system: {
      eyebrow: "01 — What makes us unique",
      title: "What makes us unique.",
      intro:
        "At Cellulift, our strength lies in creativity and advice. We put in place the mechanisms best suited to the way you work, to help you carry out your project.",
      pillars: [
        { code: "01", name: "Support", title: "Responsiveness, listening and advice", text: "The Cellulift team supports its clients throughout their professional journey, from the start to the opening of your project." },
        { code: "02", name: "Installation", title: "Everywhere in Morocco", text: "Suitable transport, assembly and installation of your devices by our experts: we keep your equipment safe and spare you the technical side." },
        { code: "03", name: "Training", title: "Cellulift Academy", text: "Nationally and internationally renowned physicians and specialists to make you an expert in aesthetic medicine." },
        { code: "04", name: "After-sales service", title: "Our workshop", text: "Breakdown, technical issue or simply a question: our workshop welcomes your devices in the best conditions." },
      ],
    },
    why: {
      eyebrow: "03 — Why Cellulift?",
      title: "Why Cellulift?",
      intro: "You get a unique service with our team of experts. Support, advice and solutions are our watchwords.",
      items: [
        { title: "Official LGL Expert distributor", text: "Cellulift is the official distributor of the LGL Expert brand in Africa." },
        { title: "CE and FDA certified", text: "All our devices are CE and FDA certified." },
        { title: "24-month warranty", text: "Parts and labour, with on-site visits by our technical staff." },
        { title: "The best trainers", text: "National and international, university professors and body and well-being experts." },
        { title: "Since 2002", text: "Over 20 years of expertise in medical aesthetic devices." },
      ],
    },
    technologies: {
      eyebrow: "02 — Technologies",
      title: "Our technologies,",
      titleAccent: "by treatment type.",
      intro: "Latest-generation LGL Expert devices, of which Cellulift is the official distributor in Africa, all CE Medical and FDA certified.",
      columns: { ref: "", name: "", category: "", indications: "" },
      viewAll: "Explore the technologies",
    },
    academy: {
      eyebrow: "04 — Cellulift Academy",
      title: "Become an expert in aesthetic medicine.",
      text: "Training, workshops and meetings around the body and well-being. Rejuvenation, slimming, physiotherapy and face or body treatments will hold no more secrets for you. A certificate confirms the skills acquired.",
      facultyLabel: "Trainer",
      cta: "See upcoming training",
    },
    support: {
      eyebrow: "05 — After-sales service",
      title: "Our engineers and technicians are there for you, everywhere.",
      text: "Because our partners' well-being comes first, we chose the best in the profession to support you when needed.",
      items: [
        { code: "01", title: "24-month warranty", text: "Parts and labour." },
        { code: "02", title: "On-site visits", text: "Our technical staff can come to you." },
        { code: "03", title: "Our workshop", text: "Your devices welcomed in the best conditions." },
        { code: "04", title: "Advice", text: "A technical question? Our team answers." },
      ],
      cta: "Book now",
    },
    showrooms: {
      eyebrow: "06 — Locations",
      title: ["One partner.", "Four markets."],
      markets: ["Morocco", "France", "Senegal", "Saudi Arabia"],
      hq: "Head office",
      onRequest: "Address shared by appointment.",
      cta: "Book a showroom visit",
      list: "Showrooms",
    },
    cta: {
      eyebrow: "07 — Our promise",
      title: "Get a free quote.",
      text: "We are committed to welcoming you warmly and professionally, in a friendly setting, to respecting your requests and listening to your expectations.",
      ctaPrimary: "Request a quote",
      ctaSecondary: "Call us",
    },
  },
} as const;
