// Accueil Cellulift — textes repris de cellulift.ma (légèrement resserrés pour les cartes).
// « {n} » = nombre de technologies du catalogue.

export const homeSystem = {
  fr: {
    hero: {
      eyebrow: "Cellulift · Depuis 2002 · Casablanca · Marrakech · Tanger",
      title: ["Complice", "de votre succès."],
      stagger: ["Complice", "de votre", "succès."],
      titleAccent: "Cellulift propose des solutions haut de gamme pour percer dans votre activité.",
      subtitle: "Leader sur le marché des équipements médicaux et spécialisé dans les dispositifs médico-esthétiques.",
      backdrop: ["Medical", "Aesthetic"],
      corner: "Toutes nos machines sont certifiées CE et FDA, avec une garantie de 24 mois pièces et main-d'œuvre.",
      cornerStrong: "Depuis 2002 à vos côtés.",
      ctaPrimary: "Obtenez un devis gratuit",
      ctaSecondary: "Nos {n} produits",
      readout: { label: "Cellulift", status: "", output: "" },
    },
    system: {
      eyebrow: "01 — Nos fonctionnalités uniques",
      title: "Nos fonctionnalités uniques.",
      intro:
        "Chez Cellulift, nous cultivons notre force dans la créativité et le conseil. Nous mettons en place les mécanismes les plus adaptés à votre fonctionnement pour vous accompagner à réaliser au mieux votre projet.",
      pillars: [
        {
          code: "01",
          name: "Accompagnement",
          title: "Réactivité, écoute et conseil",
          text: "L'équipe Cellulift accompagne ses clients tout le long de leur trajet professionnel, du début jusqu'à l'inauguration de votre projet.",
        },
        {
          code: "02",
          name: "Installation",
          title: "Partout au Maroc",
          text: "Transport adapté, montage et installation de vos machines par nos experts : nous assurons la sécurité de votre matériel et vous épargnons toute la partie technique.",
        },
        {
          code: "03",
          name: "Formation",
          title: "Cellulift Academy",
          text: "Des médecins et spécialistes de renommée nationale et internationale pour faire de vous un expert en médecine esthétique.",
        },
        {
          code: "04",
          name: "Service après-vente",
          title: "Notre atelier",
          text: "En cas de panne, de problème technique ou simplement d'un besoin de conseil, notre atelier accueille vos machines dans les meilleures conditions.",
        },
      ],
    },
    why: {
      eyebrow: "02 — Pourquoi Cellulift ?",
      title: "Pourquoi Cellulift ?",
      intro: "Vous disposerez d'un service unique avec notre équipe d'experts. Accompagnement, conseils et solutions sont nos maîtres mots.",
      items: [
        { title: "Certifiées CE et FDA", text: "Toutes nos machines sont certifiées CE et FDA." },
        { title: "Garantie 24 mois", text: "Pièces et main-d'œuvre, avec possibilité de déplacement du staff technique." },
        { title: "Marques en exclusivité", text: "Nous représentons plusieurs marques internationales en exclusivité." },
        { title: "Les meilleurs formateurs", text: "Nationaux et internationaux, professeurs universitaires et experts du corps et de son bien-être." },
        { title: "400 m² de showroom", text: "Au cœur du quartier des Hôpitaux, pour découvrir les dernières nouveautés de la technologie médicale." },
        { title: "Depuis 2002", text: "Plus de 20 ans d'expertise dans les dispositifs médico-esthétiques." },
      ],
    },
    technologies: {
      eyebrow: "03 — Nos produits",
      title: "{n} technologies. Cinq familles.",
      intro: "Les meilleurs dispositifs de dernière génération de nos marques partenaires, tous certifiés CE Médical et FDA et réputés pour leur fiabilité.",
      columns: { ref: "", name: "", category: "", indications: "" },
      viewAll: "Voir tous nos produits",
    },
    academy: {
      eyebrow: "04 — Cellulift Academy",
      title: "Devenez expert en médecine esthétique.",
      text: "Formations, workshops et rencontres autour du corps et de sa pleine forme. Rajeunissement, amincissement, physiothérapie et soins du visage ou du corps n'auront plus aucun secret pour vous. Un certificat valide les compétences acquises.",
      facultyLabel: "Formateur",
      cta: "Voir les prochaines formations",
    },
    support: {
      eyebrow: "05 — Service après-vente",
      title: "Nos ingénieurs et techniciens sont à votre écoute, partout.",
      text: "Parce que le bien-être de nos partenaires est primordial, nous avons choisi les meilleurs de la profession pour vous accompagner en cas de besoin.",
      items: [
        { code: "01", title: "Garantie 24 mois", text: "Pièces et main-d'œuvre." },
        { code: "02", title: "Déplacement", text: "Notre staff technique peut se déplacer chez vous." },
        { code: "03", title: "Notre atelier", text: "Vos machines accueillies dans les meilleures conditions." },
        { code: "04", title: "Conseil", text: "Une question technique ? Notre équipe vous répond." },
      ],
      cta: "Réserver maintenant",
    },
    testimonials: {
      eyebrow: "06 — Témoignages",
      title: "Ils nous font confiance.",
      rating: "Excellent",
      count: "Basé sur 12 avis Google",
      quotes: [
        {
          text: "Je recommande la société Cellulift à toute personne désirant établir un vrai partenariat de long terme et pratiquer son métier d'une manière sereine, sans contrainte de service après-vente ni de disponibilité de pièces. Ce sont des gens de parole qui respectent leurs engagements. Je ne regrette pas mon choix.",
          author: "Video Une variété",
        },
        { text: "Excellente équipe, excellent service. Bon courage.", author: "Joudia El" },
      ],
    },
    showrooms: {
      eyebrow: "07 — Nos showrooms",
      title: "Venez découvrir nos machines.",
      intro: "Six showrooms pour découvrir nos technologies avant de choisir. Cliquez sur une ville.",
      hq: "Siège · 400 m²",
      onRequest: "Adresse communiquée sur rendez-vous.",
      cta: "Prendre rendez-vous au showroom",
      list: "Showrooms",
    },
    cta: {
      eyebrow: "08 — Notre belle promesse",
      title: "Obtenez un devis gratuit.",
      text: "Nous nous engageons à vous accueillir amicalement et professionnellement, dans un cadre convivial et chaleureux, à respecter vos demandes et à être à l'écoute de vos attentes.",
      ctaPrimary: "Demander un devis",
      ctaSecondary: "Nous appeler",
    },
  },
  en: {
    hero: {
      eyebrow: "Cellulift · Since 2002 · Casablanca · Marrakech · Tangier",
      title: ["Partner", "in your success."],
      stagger: ["Partner", "in your", "success."],
      titleAccent: "Cellulift offers high-end solutions to help your practice break through.",
      subtitle: "A leader in the medical equipment market, specialized in medical aesthetic devices.",
      backdrop: ["Medical", "Aesthetic"],
      corner: "All our devices are CE and FDA certified, with a 24-month parts and labour warranty.",
      cornerStrong: "By your side since 2002.",
      ctaPrimary: "Get a free quote",
      ctaSecondary: "Our {n} products",
      readout: { label: "Cellulift", status: "", output: "" },
    },
    system: {
      eyebrow: "01 — What makes us unique",
      title: "What makes us unique.",
      intro:
        "At Cellulift, our strength lies in creativity and advice. We put in place the mechanisms best suited to the way you work, to help you carry out your project.",
      pillars: [
        { code: "01", name: "Support", title: "Responsiveness, listening and advice", text: "The Cellulift team supports its clients throughout their professional journey, from the start to the opening of your project." },
        { code: "02", name: "Installation", title: "Everywhere in Morocco", text: "Suitable transport, assembly and installation of your devices by our experts: we keep your equipment safe and spare you the technical side." },
        { code: "03", name: "Training", title: "Cellulift Academy", text: "Nationally and internationally renowned physicians and specialists to make you an expert in aesthetic medicine." },
        { code: "04", name: "After-sales service", title: "Our workshop", text: "Breakdown, technical issue or simply a question: our workshop welcomes your devices in the best conditions." },
      ],
    },
    why: {
      eyebrow: "02 — Why Cellulift?",
      title: "Why Cellulift?",
      intro: "You get a unique service with our team of experts. Support, advice and solutions are our watchwords.",
      items: [
        { title: "CE and FDA certified", text: "All our devices are CE and FDA certified." },
        { title: "24-month warranty", text: "Parts and labour, with on-site visits by our technical staff." },
        { title: "Exclusive brands", text: "We exclusively represent several international brands." },
        { title: "The best trainers", text: "National and international, university professors and body and well-being experts." },
        { title: "400 m² showroom", text: "In the heart of the Hospitals district, to discover the latest medical technology." },
        { title: "Since 2002", text: "Over 20 years of expertise in medical aesthetic devices." },
      ],
    },
    technologies: {
      eyebrow: "03 — Our products",
      title: "{n} technologies. Five families.",
      intro: "The latest-generation devices from our partner brands, all CE Medical and FDA certified and known for their reliability.",
      columns: { ref: "", name: "", category: "", indications: "" },
      viewAll: "See all our products",
    },
    academy: {
      eyebrow: "04 — Cellulift Academy",
      title: "Become an expert in aesthetic medicine.",
      text: "Training, workshops and meetings around the body and well-being. Rejuvenation, slimming, physiotherapy and face or body treatments will hold no more secrets for you. A certificate confirms the skills acquired.",
      facultyLabel: "Trainer",
      cta: "See upcoming training",
    },
    support: {
      eyebrow: "05 — After-sales service",
      title: "Our engineers and technicians are there for you, everywhere.",
      text: "Because our partners' well-being comes first, we chose the best in the profession to support you when needed.",
      items: [
        { code: "01", title: "24-month warranty", text: "Parts and labour." },
        { code: "02", title: "On-site visits", text: "Our technical staff can come to you." },
        { code: "03", title: "Our workshop", text: "Your devices welcomed in the best conditions." },
        { code: "04", title: "Advice", text: "A technical question? Our team answers." },
      ],
      cta: "Book now",
    },
    testimonials: {
      eyebrow: "06 — Testimonials",
      title: "They trust us.",
      rating: "Excellent",
      count: "Based on 12 Google reviews",
      quotes: [
        {
          text: "I recommend Cellulift to anyone who wants a real long-term partnership and to practice with peace of mind, without worrying about after-sales service or parts availability. They keep their word and honor their commitments. I don't regret my choice.",
          author: "Video Une variété",
        },
        { text: "Excellent team, excellent service. Keep it up.", author: "Joudia El" },
      ],
    },
    showrooms: {
      eyebrow: "07 — Our showrooms",
      title: "Come and discover our devices.",
      intro: "Six showrooms to discover our technologies before choosing. Click on a city.",
      hq: "Head office · 400 m²",
      onRequest: "Address shared by appointment.",
      cta: "Book a showroom visit",
      list: "Showrooms",
    },
    cta: {
      eyebrow: "08 — Our promise",
      title: "Get a free quote.",
      text: "We are committed to welcoming you warmly and professionally, in a friendly setting, to respecting your requests and listening to your expectations.",
      ctaPrimary: "Request a quote",
      ctaSecondary: "Call us",
    },
  },
} as const;
