// Accueil Cellulift — textes repris de cellulift.ma (légèrement resserrés pour les cartes).
// Textes de l'accueil.

export const homeSystem = {
  fr: {
    hero: {
      // Ligne de contexte (H1, pour le référencement) puis grand titre de marque.
      seo: "Technologies médico-esthétiques professionnelles",
      title: ["La technologie", "au service de votre développement."],
      titleAccent: "Expertise · Formation · Installation · Support",
      badges: ["Distributeur officiel LGL Expert · Afrique", "Certifiées CE & FDA · Garantie 24 mois"],
      ctaPrimary: "Voir la technologie en action",
      ctaSecondary: "Trouver la technologie adaptée",
    },
    // Chiffres clés (très grand, sans paragraphe). « {s} » = nombre de showrooms. Ne jamais afficher le nombre de technologies.
    stats: [
      { value: "20+", label: "Ans d'expertise" },
      { value: "1000+", label: "Médecins équipés" },
      { value: "24", unit: "mois", label: "De garantie" },
      { value: "{s}", label: "Points de vente" },
    ],
    // Bandeau défilant sous le hero.
    ticker: [
      "Toutes nos machines sont certifiées CE et FDA",
      "Depuis 2002",
      "Technologies • Installation • Formation • Accompagnement • Service après-vente",
      "{s} points de vente",
      "3 pays : Maroc · France · Sénégal",
      "+1000 médecins équipés",
    ],
    system: {
      eyebrow: "02 — L'écosystème Cellulift",
      title: "Bien plus qu'une technologie.",
      intro: "",
      pillars: [
        { code: "01", name: "Conseil", title: "Choisir.", text: "Nos experts vous aident à choisir la technologie adaptée à votre activité, du premier échange jusqu'à l'inauguration de votre projet." },
        { code: "02", name: "Installation", title: "Déployer.", text: "Transport adapté, montage et mise en service par nos techniciens, partout au Maroc : vous n'avez rien à gérer côté technique." },
        { code: "03", name: "Academy", title: "Maîtriser.", text: "Formations, protocoles et workshops avec des médecins formateurs pour maîtriser chaque technologie." },
        { code: "04", name: "Support", title: "Continuer.", text: "Garantie 24 mois, déplacement du staff technique et atelier intégré : nous restons présents après l'installation." },
      ],
    },
    why: {
      eyebrow: "03 — Pourquoi Cellulift",
      title: "Pourquoi Cellulift ?",
      intro: "",
      // Preuves, présentées comme des données : la valeur domine, le libellé reste discret.
      items: [
        { label: "Distribution officielle", value: "LGL Expert", title: "Partenaire officiel en Afrique", text: "" },
        { label: "Technologies certifiées", value: "CE · FDA", title: "Toutes nos machines sont certifiées", text: "" },
        { label: "Présence internationale", value: "Maroc · France · Sénégal", title: "Accompagnement multi-marchés", text: "" },
        { label: "Expertise médicale", value: "Médecins · Formateurs · Experts", title: "Protocoles et accompagnement clinique", text: "" },
      ],
    },
    technologies: {
      eyebrow: "01 — Technologies",
      title: "Des technologies",
      titleAccent: "pour chaque indication.",
      intro: "Les dispositifs de dernière génération LGL Expert, dont Cellulift est le distributeur officiel en Afrique, tous certifiés CE Médical et FDA.",
      columns: { ref: "", name: "", category: "", indications: "" },
      viewAll: "Explorer nos technologies",
    },
    academy: {
      eyebrow: "02 — Cellulift Academy",
      title: "La technologie s'acquiert. La maîtrise se construit.",
      subtitle: "De l'installation à la maîtrise clinique.",
      text: "Formation initiale · Protocoles · Workshops · Perfectionnement",
      steps: ["Installation", "Formation", "Protocoles", "Maîtrise"],
      facultyLabel: "Formateur",
      cta: "Choisir ma prochaine formation",
    },
    support: {
      eyebrow: "03 — Support",
      title: "Après l'installation, nous restons là.",
      text: "",
      items: [
        { code: "01", title: "Garantie 24 mois", text: "Pièces et main-d'œuvre." },
        { code: "02", title: "Déplacement", text: "Notre staff technique se déplace chez vous." },
        { code: "03", title: "Atelier intégré", text: "Diagnostic et réparation de vos machines." },
        { code: "04", title: "Assistance", text: "Une question technique ? Notre équipe vous répond." },
      ],
      cta: "Obtenir de l'aide technique",
      phoneLabel: "Ligne support",
    },
    showrooms: {
      eyebrow: "04 — Implantations",
      title: ["Un partenaire.", "Trois marchés."],
      markets: ["Maroc", "France", "Sénégal"],
      hq: "Siège",
      onRequest: "Adresse communiquée sur rendez-vous.",
      cta: "Voir les machines au showroom",
      list: "Points de vente",
    },
    cta: {
      eyebrow: "05 — Votre projet",
      title: "Votre prochaine technologie commence ici.",
      text: "Parlez de votre projet à un expert Cellulift.",
      ctaPrimary: "Parler à un expert",
      ctaSecondary: "Voir la technologie en action",
    },
  },
  en: {
    hero: {
      seo: "Medical aesthetic technology for professionals",
      title: ["Medical aesthetic technology.", "Built for growth."],
      titleAccent: "Technology · Training · Installation · Support",
      badges: ["Official LGL Expert distributor · Africa", "CE & FDA certified · 24-month warranty"],
      ctaPrimary: "See it in action",
      ctaSecondary: "Find the right technology",
    },
    stats: [
      { value: "20+", label: "Years of expertise" },
      { value: "1000+", label: "Physicians equipped" },
      { value: "24", unit: "months", label: "Warranty" },
      { value: "{s}", label: "Points of sale" },
    ],
    ticker: [
      "All our devices are CE and FDA certified",
      "Since 2002",
      "Technology • Installation • Training • Support • After-sales service",
      "{s} points of sale",
      "3 countries: Morocco · France · Senegal",
      "1,000+ physicians equipped",
    ],
    system: {
      eyebrow: "02 — The Cellulift ecosystem",
      title: "Beyond the machine.",
      intro: "",
      pillars: [
        { code: "01", name: "Advice", title: "Choose.", text: "Our experts help you choose the right technology for your practice, from the first conversation to the opening of your project." },
        { code: "02", name: "Installation", title: "Deploy.", text: "Suitable transport, assembly and commissioning by our technicians, everywhere in Morocco: nothing technical to handle on your side." },
        { code: "03", name: "Academy", title: "Master.", text: "Training, protocols and workshops with physician trainers to master every technology." },
        { code: "04", name: "Support", title: "Continue.", text: "24-month warranty, on-site technical staff and an in-house workshop: we stay with you after installation." },
      ],
    },
    why: {
      eyebrow: "03 — Why Cellulift",
      title: "Why Cellulift?",
      intro: "",
      items: [
        { label: "Official distribution", value: "LGL Expert", title: "Official partner in Africa", text: "" },
        { label: "Certified technology", value: "CE · FDA", title: "All our devices are certified", text: "" },
        { label: "International presence", value: "Morocco · France · Senegal", title: "Multi-market support", text: "" },
        { label: "Medical expertise", value: "Physicians · Trainers · Experts", title: "Protocols and clinical guidance", text: "" },
      ],
    },
    technologies: {
      eyebrow: "01 — Technologies",
      title: "Technology",
      titleAccent: "for every indication.",
      intro: "Latest-generation LGL Expert devices, of which Cellulift is the official distributor in Africa, all CE Medical and FDA certified.",
      columns: { ref: "", name: "", category: "", indications: "" },
      viewAll: "Explore our technologies",
    },
    academy: {
      eyebrow: "02 — Cellulift Academy",
      title: "Technology can be acquired. Mastery is built.",
      subtitle: "From installation to clinical mastery.",
      text: "Initial training · Protocols · Workshops · Advanced courses",
      steps: ["Installation", "Training", "Protocols", "Mastery"],
      facultyLabel: "Trainer",
      cta: "Pick my next training",
    },
    support: {
      eyebrow: "03 — Support",
      title: "After installation, we stay with you.",
      text: "",
      items: [
        { code: "01", title: "24-month warranty", text: "Parts and labour." },
        { code: "02", title: "On-site visits", text: "Our technical staff comes to you." },
        { code: "03", title: "In-house workshop", text: "Diagnosis and repair of your devices." },
        { code: "04", title: "Assistance", text: "A technical question? Our team answers." },
      ],
      cta: "Get technical help",
      phoneLabel: "Support line",
    },
    showrooms: {
      eyebrow: "04 — Locations",
      title: ["One partner.", "Three markets."],
      markets: ["Morocco", "France", "Senegal"],
      hq: "Head office",
      onRequest: "Address shared by appointment.",
      cta: "See the devices at the showroom",
      list: "Points of sale",
    },
    cta: {
      eyebrow: "05 — Your project",
      title: "Your next technology starts here.",
      text: "Talk to a Cellulift expert about your project.",
      ctaPrimary: "Talk to an expert",
      ctaSecondary: "See it in action",
    },
  },
} as const;
